name:                haskell-boolean-algebra
version:             0.1.0.0
github:              "asoran/haskell-boolean-algebra"
license:             MIT
author:              "Altan Soran, Guillaume Cau"
maintainer:          "example@example.com"
copyright:           "2020 Altan Soran, Guillaume Cau"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/asoran/haskell-boolean-algebra#readme>

dependencies:
- base >= 4.7 && < 5
# - containers >= 0.6
# - split >= 0.2

library:
  source-dirs: src
#  exposed-modules:
#    - Data.Logic.Var
#    - Data.Logic.Var.Some
#    - Data.Logic.Fml
#    - Data.Logic.Fml.Some
#    - Data.Logic.Fml.Combinator

# executables:
#   haskell-boolean-algebra-exe:
#     main:                Main.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - haskell-boolean-algebra

tests:
  haskell-boolean-algebra-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-boolean-algebra
    - hspec
